# This script is for the avr_host environment.
#
# It integrated the mcs51 binary with the avr_host program by using 'xxd' to
# generate a C file containing the binary generated by the mcs51 environment,
# and compile that into the avr_host binary.

Import("env")
import subprocess
import os
import shutil

# Teach SCons how to make a C file from a .bin.
def xxd_generator(target, source, env):
    src = str(source[0])
    tgt = str(target[0])
    var_name = os.path.splitext(os.path.basename(src))[0].replace("-", "_").replace(".", "_")

    result = subprocess.run(["xxd", "-i", "-n", var_name, src],
        capture_output=True, text=True, check=True)

    # Massage the output a bit to get it into a compilable form, using modern
    # types.
    with open(tgt, "w") as f:
        f.write("#include <stdint.h>\n#include <avr/pgmspace.h>\n\n")
        f.write(result.stdout
            .replace("unsigned char ", "const uint8_t ")
            .replace("[] =", "[] PROGMEM =")
            .replace("unsigned int ", "const uint16_t "))

def xxd_emitter(target, source, env):
    build_dir = env.subst("$BUILD_DIR")
    return [f"{build_dir}/xxd_gen/{os.path.splitext(os.path.basename(str(s)))[0]}.c"
            for s in source], source

env.Append(BUILDERS={"XxdBin": env.Builder(
    action=xxd_generator,
    emitter=xxd_emitter,
    suffix=".c",
    src_suffix=".bin"
)})
env['BUILDERS']['Object'].add_src_builder('XxdBin')

build_dir = env.subst("$BUILD_DIR")
mcs51_bin = os.path.abspath(f"{build_dir}/../mcs51/firmware.bin")
local_bin = f"{build_dir}/xxd_gen/firmware.bin"

# PlatformIO seems to not like files from other environments' build folders
# being used as 'source' files, so we link the file into this the current build
# folder before using it.
os.makedirs(f"{build_dir}/xxd_gen", exist_ok=True)
if os.path.exists(mcs51_bin):
    try:
        os.symlink(mcs51_bin, local_bin)
    except FileExistsError:
        pass

# Add the .bin file to the list of files to be 'built' - SCons will take care
# of the rest thanks to the setup above.
env.Append(PIOBUILDFILES=env.Object(env.XxdBin(local_bin)))